start:
	npx expo start

# This kills the port but I'm not to sure if this is the best way to do it.
#stop:
#	@echo "Stopping Expo frontend"
#	@npx kill-port 8081 || echo "Expo not running on port 8081"